/* 
 * Autor: Suzane A. hora
 * Objetivo: arquivo resposanvel pela validação, consistencia das requisições da API de filmes
 * data: 01.02.24
 * Versão: 1.0
 * 
 */


// função para validar e inserir um novo filme 
const setInserirNovoFilme = async function(){

}

// função para validar e atualizar um filme 
const setAtulizarFilme = async function(){

}


// função para validar e exclui um filme 
const setExcluirFilme = async function(){

}


// função para retornar todos os filmes
const getListarFilmes = async function(){

}

// função para buscar um filme pelo ID
const getBuscarFilmes = async function(){

}

module.exports = {

    setInserirNovoFilme,
    setAtulizarFilme,
    setExcluirFilme,
    getListarFilmes,
    getBuscarFilmes

}